piholeARPTable service setup 2

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 _pkgver=6.0.5
-_pkgrel=2
+_pkgrel=3
 source_core="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
 dira="pi-hole-$_pkgver"
 dirb="$dira.cust"
@@ -37,7 +37,9 @@ sed -i 's/^WEB_HASH=.*$/WEB_HASH="builtfromreleasetarball"/' "$dirb"/advanced/Sc
 
 # the return of service management
 sed -i "s|service pihole-FTL restart|systemctl restart pihole-FTL|w $_ssc" "$dirb"/advanced/Scripts/piholeARPTable.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management 1" && exit 1 ; fi
+sed -i "s|service pihole-FTL stop|systemctl stop pihole-FTL|w $_ssc" "$dirb"/advanced/Scripts/piholeARPTable.sh
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management 2" && exit 1 ; fi
 
 # setting up and securing pihole wrapper script
 #sed -n "/debugFunc() {/w $_ssc" "$dirb"/pihole
