using original run paths

diff --git a/patchgen b/patchgen
--- a/patchgen
+++ b/patchgen
@@ -134,14 +134,10 @@ sed -i "s|/var/log/pihole/pihole.log|/run/log/pihole/pihole.log|g" "$dirb"/advan
 # -----------------
 
 # change log and bin location to logrotate
-sed -i "s|/var/log/pihole/pihole.log|/run/log/pihole/pihole.log|w $_ssc" "$dirb"/advanced/Templates/logrotate
+sed -i "s|/var/log/pihole|/run/log/pihole|w $_ssc" "$dirb"/advanced/Templates/logrotate
 if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 1" && exit 1 ; fi
-sed -i "s|/var/log/pihole/FTL.log|/run/log/pihole-ftl/pihole-FTL.log|w $_ssc" "$dirb"/advanced/Templates/logrotate
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 2" && exit 1 ; fi
 sed -i "s|/usr/sbin|/usr/bin|w $_ssc" "$dirb"/advanced/Scripts/piholeLogFlush.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 3" && exit 1 ; fi
-sed -i "s|/var/lib/logrotate/pihole|/var/lib/logrotate_pihole.status|w $_ssc" "$dirb"/advanced/Scripts/piholeLogFlush.sh
-if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 3" && exit 1 ; fi
+if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change log and bin location to logrotate 2" && exit 1 ; fi
 
 # -----------------
 
